games:
  ttt:
    delay: 10
    ip: lexodexo.de
    port: 27015
  csgo:
    delay: 10
    ip: f4814n.de
    port: 27015

players:
  fabian:
    nicks:
      ttt: d4rkshad0w
  lukas:
    nicks:
      ttt: Meinzzz
      csgo: Meinzzz

server: true

database:
  path: ":memory:"
